### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [jordphilli/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
     -Please include a link to the source code of the .md file (github link to the file should fine)
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
    -Please include a link to the source code of the .md file (github link to the file should fine)
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
     -Please include a link to the source code of the test-input file
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:

Feel free to comment below if you have any questions about the rubric/feedback.
Great job :)
--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by jordphilli** [comment]
I am confused by why I did not receive points for the test files. I included them in the code, maybe they were hard to see? Did the links not work?

**Comment by yahmad3495** [comment]
Hey Jordan, sorry I think the links weren't working for some reason when I first checked it out. I'll update your grade.
